# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7cebbf0cfc82f6f09e08969736e74b13f6ffb56b23e9343072cb327f7610197ca7d9357098f0113dc187ce47369cc6251cfc39d24c55f5116f19ab6a03c92651

test:
  secret_key_base: 59e8d7ef7e354906003d12d98e7399ae865e256a09abc628ab59f6198a4ff8b65a09be0fff54ba8337b444c8fca5b1a48ed073eb40a2e134fd2f66b37c2e64d9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
